### ISSUE TITLE
[PE-D] Maybe update Appointments such that everything that is found under 'find' is shown.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T11-3/tp#184]
May be confusing if the Appointment section is blank, and the list of doctors is empty.

![Screenshot 2021-10-29 164334.png](https://raw.githubusercontent.com/GWphua/ped/main/files/0dd88c43-ce30-4c14-8dcc-3106ce7d10ce.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: GWphua/ped#7

**Comment by jiayi1129** [comment]
If you `find` then `delete` after then it will show No doctors found.
