### ISSUE TITLE
[PE-D] Duplicate doctors 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T11-3/tp#189]
Expect to not be able to add doctors with the same name, age, address and email address, but able to without any warning or errors.

![image.png](https://raw.githubusercontent.com/ailing35/ped/main/files/660f74ae-00ba-4bc6-8de5-f1f16f6f4f2c.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ailing35/ped#7

**Comment by jiayi1129** [comment]
If the patient has a son then the phone and email will be the same, so there will not be any point in changing to a less strict equality.
